//
//  CurveData.m
//  XLApp
//
//  Created by JY on 14-3-10.
//  Copyright (c) 2014年 Pixel-in-Gene. All rights reserved.
//

#import "CurveData.h"


@implementation CurveData

@dynamic cvAvg;
@dynamic cvBeginDate;
@dynamic cvCurveDensity;
@dynamic cvCurvePoints;
@dynamic cvCurveType;
@dynamic cvMeasureNo;
@dynamic cvPoint1;
@dynamic cvPoint2;
@dynamic cvPoint3;
@dynamic cvPoint4;
@dynamic cvPoint5;
@dynamic cvPoint6;
@dynamic cvPoint7;
@dynamic cvPoint8;
@dynamic cvPoint9;
@dynamic cvPoint10;
@dynamic cvPoint11;
@dynamic cvPoint12;
@dynamic cvPoint13;
@dynamic cvPoint14;
@dynamic cvPoint15;
@dynamic cvPoint16;
@dynamic cvPoint17;
@dynamic cvPoint18;
@dynamic cvPoint19;
@dynamic cvPoint20;
@dynamic cvPoint21;
@dynamic cvPoint22;
@dynamic cvPoint23;
@dynamic cvPoint24;
@dynamic cvPoint25;
@dynamic cvPoint26;
@dynamic cvPoint27;
@dynamic cvPoint28;
@dynamic cvPoint29;
@dynamic cvPoint30;
@dynamic cvPoint31;
@dynamic cvPoint32;
@dynamic cvPoint33;
@dynamic cvPoint34;
@dynamic cvPoint35;
@dynamic cvPoint36;
@dynamic cvPoint37;
@dynamic cvPoint38;
@dynamic cvPoint39;
@dynamic cvPoint40;
@dynamic cvPoint41;
@dynamic cvPoint42;
@dynamic cvPoint43;
@dynamic cvPoint44;
@dynamic cvPoint45;
@dynamic cvPoint46;
@dynamic cvPoint47;
@dynamic cvPoint48;
@dynamic cvPoint49;
@dynamic cvPoint50;
@dynamic cvPoint51;
@dynamic cvPoint52;
@dynamic cvPoint53;
@dynamic cvPoint54;
@dynamic cvPoint55;
@dynamic cvPoint56;
@dynamic cvPoint57;
@dynamic cvPoint58;
@dynamic cvPoint59;
@dynamic cvPoint60;
@dynamic cvPoint61;
@dynamic cvPoint62;
@dynamic cvPoint63;
@dynamic cvPoint64;
@dynamic cvPoint65;
@dynamic cvPoint66;
@dynamic cvPoint67;
@dynamic cvPoint68;
@dynamic cvPoint69;
@dynamic cvPoint70;
@dynamic cvPoint71;
@dynamic cvPoint72;
@dynamic cvPoint73;
@dynamic cvPoint74;
@dynamic cvPoint75;
@dynamic cvPoint76;
@dynamic cvPoint77;
@dynamic cvPoint78;
@dynamic cvPoint79;
@dynamic cvPoint80;
@dynamic cvPoint81;
@dynamic cvPoint82;
@dynamic cvPoint83;
@dynamic cvPoint84;
@dynamic cvPoint85;
@dynamic cvPoint86;
@dynamic cvPoint87;
@dynamic cvPoint88;
@dynamic cvPoint89;
@dynamic cvPoint90;
@dynamic cvPoint91;
@dynamic cvPoint92;
@dynamic cvPoint93;
@dynamic cvPoint94;
@dynamic cvPoint95;
@dynamic cvPoint96;
@dynamic cvUpdateTime;
@dynamic epId;
@dynamic cvMax;
@dynamic cvMaxTime;
@dynamic cvMin;
@dynamic cvMinTime;
@dynamic cvDataTime;

@end
