//
//  CurveDataNew.m
//  XLApp
//
//  Created by JY on 14-3-9.
//  Copyright (c) 2014年 Pixel-in-Gene. All rights reserved.
//

#import "CurveDataNew.h"

@implementation CurveDataNew

@synthesize epId;
@synthesize cvMeasureNo;
@synthesize cvBeginDate;
@synthesize cvCurveDensity;
@synthesize cvCurvePoints;
@synthesize cvCurveType;
@synthesize cvPoint1;
@synthesize cvPoint2;
@synthesize cvPoint3;
@synthesize cvPoint4;
@synthesize cvPoint5;
@synthesize cvPoint6;
@synthesize cvPoint7;
@synthesize cvPoint8;
@synthesize cvPoint9;
@synthesize cvPoint10;
@synthesize cvPoint11;
@synthesize cvPoint12;
@synthesize cvPoint13;
@synthesize cvPoint14;
@synthesize cvPoint15;
@synthesize cvPoint16;
@synthesize cvPoint17;
@synthesize cvPoint18;
@synthesize cvPoint19;
@synthesize cvPoint20;
@synthesize cvPoint21;
@synthesize cvPoint22;
@synthesize cvPoint23;
@synthesize cvPoint24;
@synthesize cvPoint25;
@synthesize cvPoint26;
@synthesize cvPoint27;
@synthesize cvPoint28;
@synthesize cvPoint29;
@synthesize cvPoint30;
@synthesize cvPoint31;
@synthesize cvPoint32;
@synthesize cvPoint33;
@synthesize cvPoint34;
@synthesize cvPoint35;
@synthesize cvPoint36;
@synthesize cvPoint37;
@synthesize cvPoint38;
@synthesize cvPoint39;
@synthesize cvPoint40;
@synthesize cvPoint41;
@synthesize cvPoint42;
@synthesize cvPoint43;
@synthesize cvPoint44;
@synthesize cvPoint45;
@synthesize cvPoint46;
@synthesize cvPoint47;
@synthesize cvPoint48;
@synthesize cvPoint49;
@synthesize cvPoint50;
@synthesize cvPoint51;
@synthesize cvPoint52;
@synthesize cvPoint53;
@synthesize cvPoint54;
@synthesize cvPoint55;
@synthesize cvPoint56;
@synthesize cvPoint57;
@synthesize cvPoint58;
@synthesize cvPoint59;
@synthesize cvPoint60;
@synthesize cvPoint61;
@synthesize cvPoint62;
@synthesize cvPoint63;
@synthesize cvPoint64;
@synthesize cvPoint65;
@synthesize cvPoint66;
@synthesize cvPoint67;
@synthesize cvPoint68;
@synthesize cvPoint69;
@synthesize cvPoint70;
@synthesize cvPoint71;
@synthesize cvPoint72;
@synthesize cvPoint73;
@synthesize cvPoint74;
@synthesize cvPoint75;
@synthesize cvPoint76;
@synthesize cvPoint77;
@synthesize cvPoint78;
@synthesize cvPoint79;
@synthesize cvPoint80;
@synthesize cvPoint81;
@synthesize cvPoint82;
@synthesize cvPoint83;
@synthesize cvPoint84;
@synthesize cvPoint85;
@synthesize cvPoint86;
@synthesize cvPoint87;
@synthesize cvPoint88;
@synthesize cvPoint89;
@synthesize cvPoint90;
@synthesize cvPoint91;
@synthesize cvPoint92;
@synthesize cvPoint93;
@synthesize cvPoint94;
@synthesize cvPoint95;
@synthesize cvPoint96;
@synthesize cvAvg;
@synthesize cvUpdateTime;
@synthesize cvMax;
@synthesize cvMaxTime;
@synthesize cvMin;
@synthesize cvMinTime;
@synthesize cvDataTime;

@end
